ChooseComponents {
    Title
    "Auswahl Komponenten"

    Subtitle
    "Wдhlen Sie die zu installierenden Komponenten aus."

    Caption
    "Wдhlen Sie die zu installierenden Komponenten aus und deselektieren Sie\
     die Komponenten, die Sie nicht installieren mцchten."

    Message
    "<%SpaceRequiredText%> an Plattenplatz benцtigt"

    DescriptionLabel
    "Beschreibung"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installation"

    Subtitle
    "Installiere <%AppName%>"

    Caption
    "Bitte warten Sie, wдhrend Setup <%AppName%> auf Ihrem Computer installiert."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Ьberschrift kommt hier hin."

    Message
    "Meldung kommt hier hin."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Titel"

    Subtitle
    "Untertitel"

    Caption
    "Ьberschrift"

    Message
    "Meldung"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Titel"

    Subtitle
    "Untertitel"

    Caption
    "Untertitel"

    Message
    "Meldung"

    Text
    "Ihr benutzerdefinierter Text kommt hier hin."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Lizenzbestimmungen"

    Subtitle
    "Bitte lesen Sie die folgenden Lizenzbestimmungen aufmerksam."

    AcceptRadiobutton
    "Ich akzeptiere die Lizenzbestimmungen."

    DeclineRadiobutton
    "Ich akzeptiere nicht die Lizenzbestimmungen."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Liesmich Informationen"

    Subtitle
    "Liesmich Informationen fьr <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Auswahl Installationsziel"

    Subtitle
    "Wohin soll <%AppName%> installiert werden?"

    Caption
    "Setup wird <%AppName%> in das folgende Verzeichnis installieren. \
    \n\nKlicken Sie auf Weiter, wenn dieses Verzeichnis verwendet werden soll. \
    Um ein anderes Verzeichnis auszuwдhlen, klicken Sie auf Durchsuchen und\
    wдhlen ein anderes aus."

    Message
    ""

    BrowseText
    "Um Fortzufahren, klicken Sie auf Weiter.  Wenn Sie ein anderes Verzeichnis\
    verwenden mцchten, klicken Sie auf Durchsuchen."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Zielordner"
}

SelectProgramFolder {
    Title
    "Auswahl Programmordner"

    Subtitle
    "Bitte wдhlen Sie einen Programmordner."

    Caption
    "Setup wird die Programmsymbole zum unten aufgefьhrten Programmordner\
    hinzufьgen. Sie kцnnen einen neuen Ordnernamen eingeben oder einen von der\
    von der existierenden Ordnerliste auswдhlen. Klicken Sie auf Weiter um\
    Fortzufahren."

    Message
    ""

    ProgramFolderLabel
    "Programmordner:"

    FolderListLabel
    "Vorhandene Ordner:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Erstelle Programmordner fьr alle Benutzer"
}

SetupComplete {
    Caption
    "Installation Abgeschlossen"

    Message
    "InstallJammer hat <%AppName%> erfolgreich installiert. \
     Klicken Sie auf Beenden, um den Assistenten zu verlassen."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Art"

    Subtitle
    "Wдhlen Sie die Art des Setup, welche am Besten Ihren Anforderungen\
    entspricht."

    Caption
    "Klicken Sie auf die bevorzugte Art des Setup."

    Message
    ""

    DescriptionLabel
    "Beschreibung"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Kopieren der Dateien"

    Subtitle
    "Ьberprьfen Sie die Einstellungen, bevor die Dateien kopiert werden."

    Caption
    "Setup hat genug Informationen, um die Programmdateien\
    zu kopieren. Wenn Sie die Einstellungen ьberprьfen oder дndern mцchten,\
    klicken Sie auf Zurьck. Wenn Sie mit den Einstellungen zufrieden sind,\
    klicken Sie auf Weiter, um mit dem Kopieren der Dateien zu beginnen."

    Message
    ""

    Text
    "Installationsverzeichnis:
                <%InstallDir%>

    Setup Art:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Deinstallation"

    Subtitle
    "Deinstalliere <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Deinstallation Abgeschlossen"

    Message
    "<%AppName%> wurde von Ihrem System entfernt."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Deinstallation Details"

    Subtitle
    "Es sind Fehler beim Lцschen aufgetreten"

    Caption
    "Die folgenden Fehler sind beim Lцschen aufgetreten:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Benutzer Information"

    Subtitle
    "Bitte geben Sie Ihre Informationen ein."

    Caption
    "Bitte geben Sie Ihren Namen und den Namen der Firma ein, fьr die Sie\
    arbeiten."

    Message
    ""

    UserNameLabel
    "Benutzername:"

    CompanyLabel
    "Firma:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Willkommen beim InstallJammer Assistenten fьr <%AppName%>"

    Message
    "Dies wird <%AppName%> Version <%Version%> auf Ihrem Computer installieren. \
    \n\nEs wird empfohlen, das Sie alle anderen Anwendungen schlieЯen, bevor\
    Sie fortfahren.\n\nKlicken Sie auf Weiter um Fortzufahren oder auf\
    Abbrechen, um das Setup zu beenden."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
