ChooseComponents {
    Title
    "Seleccionar Componentes"

    Subtitle
    "Seleccionar los componentes de la instalaciуn."

    Caption
    "Seleccione los componentes que desea instalar y elimine aquйllos\
     que no desea que sean instalados."

    Message
    "<%SpaceRequiredText%> de espacio requerido"

    DescriptionLabel
    "Descripciуn"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Instalando"

    Subtitle
    "Instalando <%AppName%>"

    Caption
    "Por favor espere mientras se instala <%AppName%> en su equipo."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Leyenda aquн."

    Message
    "Mensaje aquн."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Tнtulo"

    Subtitle
    "Subtнtulo"

    Caption
    "Leyenda"

    Message
    "Mensaje"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Tнtulo"

    Subtitle
    "Subtнtulo"

    Caption
    "Leyenda"

    Message
    "Mensaje"

    Text
    "Escriba su texto personalizado aquн."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Acuerdo de Licencia"

    Subtitle
    "Por favor lea atentamente el siguiente acuerdo de licencia."

    AcceptRadiobutton
    "Acepto los tйrminos de este acuerdo de licencia."

    DeclineRadiobutton
    "NO acepto los tйrminos de este acuerdo de licencia."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Lйeme"

    Subtitle
    "Informaciуn sobre <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Escoja Carpeta Destino"

    Subtitle
    "їDуnde desea instalar <%AppName%>?"

    Caption
    "Se instalarб <%AppName%> en la siguiente carpeta. Para instalar\
     en esta carpeta, pulse Siguiente. Para instalar en una carpeta diferente,\
     pulse Examinar y seleccione otra."

    Message
    ""

    BrowseText
    "Pulse Siguiente para continuar. Si desea seleccionar una\
    carpeta diferente, pulse Examinar."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Carpeta Destino"
}

SelectProgramFolder {
    Title
    "Seleccione Grupo de Programas"

    Subtitle
    "Por favor, seleccione un grupo de programas."

    Caption
    "Se instalarбn iconos en el Grupo de Programas siguiente.\
    Puede escribir un nuevo nombre de grupo o seleccionarlo\
    de la lista de grupos existentes.\
    Pulse Siguiente para continuar."

    Message
    ""

    ProgramFolderLabel
    "Grupo de Programas:"

    FolderListLabel
    "Grupos Existentes:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Crear grupo de programas para todos los usuarios"
}

SetupComplete {
    Caption
    "Instalaciуn Completa"

    Message
    "Se ha instalado <%AppName%> con йxito. \
     Pulse Finalizar para salir de este wizard."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Tipo de Instalaciуn"

    Subtitle
    "Seleccione el tipo de instalaciуn que mбs se ajuste a sus necesidades."

    Caption
    "Pulse el tipo de instalaciуn que prefiere."

    Message
    ""

    DescriptionLabel
    "Descripciуn"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Comenzar a Copiar Archivos"

    Subtitle
    "Revise la configuraciуn antes de copiar los archivos"

    Caption
    "Se ha recopilado la informaciуn necesaria para comenzar a copiar los\
    archivos del programa. Si desea revisar o cambiar la configuraciуn,\
    pulse Atrбs. Si estб conforme con la configuraciуn, pulse Siguiente para\
    comenzar a copiar los archivos."

    Message
    ""

    Text
    "Directorio de Instalaciуn:
            <%InstallDir%>

    Tipo de Instalaciуn:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Desinstalar"

    Subtitle
    "Desinstalar <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Desinstalaciуn Completa"

    Message
    "<%AppName%> ha sido eliminado de su sistema."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Detalles de Desinstalaciуn"

    Subtitle
    "Errores durante la eliminaciуn"

    Caption
    "Ocurrieron los siguientes errores durante el proceso de desinstalaciуn:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Informaciуn de Usuario"

    Subtitle
    "Por favor introduzca sus datos de usuario."

    Caption
    "Por favor introduzca el nombre de la empresa para la que trabaja."

    Message
    ""

    UserNameLabel
    "Nombre de Usuario:"

    CompanyLabel
    "Empresa:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Bienvenido al InstallJammer Wizard para <%AppName%>"

    Message
    "Este programa instalarб <%AppName%> versiуn <%Version%> en su equipo.\
    \n\nSe recomienda cerrar las demбs aplicaciones antes de continuar. \
    \n\nPulse Siguiente para continuar o Cancelar para salir de la instalaciуn."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
