ChooseComponents {
    Title
    "Sйlectionnez les composants"

    Subtitle
    "Sйlectionnez les composants devant кtre installйs."

    Caption
    "Sйlectionner les composants а installer et dйselectionner les composants а ne pas installer."

    Message
    "<%SpaceRequiredText%> d'espace requis"

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installation"

    Subtitle
    "Installation de <%AppName%>"

    Caption
    "Patientez pendant l'installation de <%AppName%> sur votre ordinateur."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Saisir la lйgende ici."

    Message
    "Saisir le message ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Titre"

    Subtitle
    "Sous-titre"

    Caption
    "Lйgende"

    Message
    "Message"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Titre"

    Subtitle
    "Sous-titre"

    Caption
    "Lйgende"

    Message
    "Message"

    Text
    "Saisissez votre texte personnalisй ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Accord de licence"

    Subtitle
    "Veuillez lire attentivement l'accord de licence suivant SVP."

    AcceptRadiobutton
    "J'accepte les termes de cet accord de licence."

    DeclineRadiobutton
    "Je n'accepte pas les termes de cet accord de licence."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Readme"

    Subtitle
    "Readme pour <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Sйlectionnez le rйpertoire d'installation"

    Subtitle
    "Oщ installer <%AppName%> ?"

    Caption
    "L'installation de <%AppName%> s'effectuera dans le rйpertoire suivant.\n\nPour installer\
     dans ce rйpertoire, cliquez sur le bouton SUIVANT.\n\nPour installer dans un autre rйpertoire, cliquez\
     sur le bouton PARCOURIR et sйlectionnez un autre rйpertoire."

    Message
    ""

    BrowseText
    "Pour continuer, cliquez sur SUIVANT.  Pour sйlectionner un rйpertoire\
     diffйrent, cliquez sur PARCOURIR."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Rйpertoire d'installation"
}

SelectProgramFolder {
    Title
    "Sйlectionnez le dossier Programme"

    Subtitle
    "Sйlectionnez un dossier Programme SVP."

    Caption
    "L'installation ajoutera les icфnes de programme au dossier Programme affichй ci-dessous. \
     Vous pouvez saisir un nouveau nom de dossier ou en sйlectionner un dans la liste des dossiers existants. \
     Cliquez sur SUIVANT pour continuer."

    Message
    ""

    ProgramFolderLabel
    "Dossier Programme:"

    FolderListLabel
    "Dossiers existants :"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Crйer le dossier programme pour tous les utilisateurs"
}

SetupComplete {
    Caption
    "L'assistant InstallJammer est terminй"

    Message
    "L'assistant InstallJammer a installй <%AppName%> avec succиs. \
     Cliquez sur TERMINER pour quitter l'assistant."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Type d'installation"

    Subtitle
    "Sйlectionnez le type d'installation convenant le mieux а vos besoins."

    Caption
    "Cliquez sur le type d'installation que vous souhaitez."

    Message
    ""

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Copie des fichiers"

    Subtitle
    "Contrфle du paramйtrage avant la copie de fichiers"

    Caption
    "L'installeur a maintenant assez d'informations pour commencer а copier les fichiers.  Si\
     vous voulez revoir ou modifier le paramйtrage, cliquez sur PRECEDENT.  Si vous кtes\
     satisfait du paramйtrage, cliquez sur suivant pour commencer а copier les fichiers."

    Message
    ""

    Text
    "Rйpertoire d'installation:
            <%InstallDir%>

    Type d'installation:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Dйsinstallation"

    Subtitle
    "Dйsinstallation de <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Dйsinstallation terminйe"

    Message
    "<%AppName%> a йtй dйsinstallй de votre systиme."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Details de la dйsinstallation"

    Subtitle
    "Des erreurs sont apparues pendant la dйsinstallation"

    Caption
    "Les erreurs suivantes sont apparues pendant la dйsinstallation:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Information client"

    Subtitle
    "Saisissez vos informations SVP."

    Caption
    "Saisissez votre nom et votre sociйtй."

    Message
    ""

    UserNameLabel
    "Nom:"

    CompanyLabel
    "Sociйtй:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Bienvenue dans l'assistant d'installation InstallJammer pour <%AppName%>"

    Message
    "Ceci installera <%AppName%> version <%Version%> sur votre ordinateur. \
    \n\nIl est recommandй de fermer toutes les autres applications avant\
    de continuer.\n\nCliquez sur SUIVANT pour continuer ou ANNULER pour quitter l'installation."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
