ChooseComponents {
    Title
    "Komponensek kivбlasztбsa"

    Subtitle
    "Vбlassza ki a telepнtend\u0151 komponenseket."

    Caption
    "Vбlassza ki azokat a komponenseket, amelyeket fel akar telepнteni,\
     йs ne vбlassza ki azokat, amelyeket nem akar telepнteni."

    Message
    "<%SpaceRequiredText%> szabad hely szьksйges"

    DescriptionLabel
    "Leнrбs"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Telepнtйs"

    Subtitle
    "<%AppName%> telepнtйse"

    Caption
    "Kйrem vбrjon, amнg a Telepнt\u0151 a <%AppName%> programot feltelepнti a gйpйre."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "A fejlйc jцn ide."

    Message
    "Az ьzenet jцn ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Cнm"

    Subtitle
    "Alcнm"

    Caption
    "Leнrбs"

    Message
    "Ьzenet"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Cнm"

    Subtitle
    "Alcнm"

    Caption
    "Leнrбs"

    Message
    "Ьzenet"

    Text
    "A sajбt szцvegedet rakd ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Licensz elfogadбsa"

    Subtitle
    "Kйrem olvassa el figyelmesen a kцvetkez\u0151 licensz megбllapodбst."

    AcceptRadiobutton
    "Elfogadom a licensz megбllapodбs feltйteleit."

    DeclineRadiobutton
    "Nem fogadom el a licensz megбllapodбs feltйteleit."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Olvassa el informбciуk"

    Subtitle
    "Olvassa el informбciуk a <%AppName%> alkalmazбshoz"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Vбlassza ki a cйl kцnyvtбrat"

    Subtitle
    "Hova kellene a <%AppName%> alkalmazбst telepнteni?"

    Caption
    "A telepнt\u0151 a <%AppName%> programot a kцvetkez\u0151 kцnyvtбrba telepнti.\n\n
     Ahhoz, hogy ebbe kцnyvtбrba kerьljцn kattintson a <%Next%> gombra\
     Ahhoz, hogy mбs kцnyvtбrba kerьljцn kattintson a <%Browse%> gombra."

    Message
    ""

    BrowseText
    "A folytatбshoz nyomja meg a <%Next%> gombot. \
     Ha mбsik kцnyvtбrat szeretne kivбlasztani nyomja meg a <%Browse%> gombot."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Cйl kцnyvtбr"
}

SelectProgramFolder {
    Title
    "Program mappa kivбlasztбs"

    Subtitle
    "Kйrem vбlassza ki a program mappбt!"

    Caption
    "A telepнt\u0151 a program ikonokat a lentebb listбzott Program mappбhoz fogja hozzбadni. \
	 Megvбltoztathatja az ъj mappa nevйt, vagy kivбlaszthat egy mбr lйtez\u0151t a listбrуl. \
     Kattintson a <%Next%> gombra a folytatбshoz."

    Message
    ""

    ProgramFolderLabel
    "Program mappa:"

    FolderListLabel
    "Lйtez\u0151 mappбk:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Lйtrehozza a program mappбt az цsszes felhasznбlуnak?"
}

SetupComplete {
    Caption
    "InstallJammer Varбzslу befejez\u0151dцtt"

    Message
    "Az InstallJammer Varбzslу sikeresen telepнtette a <%AppName%> alkalmazбst. \
	 Kattintson a <%Finish%> gombra ahhoz, hogy kilйpjen a varбzslуbуl."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Telepнtйs tнpusa"

    Subtitle
    "Vбlassza ki az Цnnek legjobban megfelel\u0151 telepнtйsi mуdot."

    Caption
    "Vбlassza ki a kнvбnt telepнtйsi tнpust!"

    Message
    ""

    DescriptionLabel
    "Leнrбs"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Бllomбnyok mбsolбsбnak elkezdйse"

    Subtitle
    "Tekintse бt a beбllнtбsokat, miel\u0151tt бtmбsolnбnk az бllomбnyokat!"

    Caption
    "A telepнt\u0151nek elйg informбciуja van ahhoz, hogy a program бllomбnyait\
	elkezdje mбsolni. Ha meg akarja nйzni vagy vбltoztatni a beбllнtбsokat,\
	akkor kattintson a <%Back%> gombra. Ha elйgedett a beбllнtбsokkal, akkor\
	kattintson a <%Next%> gombra, hogy elkezd\u0151djцn a fбjlok mбsolбsa."

    Message
    ""

    Text
    "Telepнtйsi kцnyvtбr:
            <%InstallDir%>

    Telepнtйs tнpusa:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Eltбvolнtбs"

    Subtitle
    "A <%AppName%> alkalmazбs eltбvolнtбsa"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Eltбvolнtбs befejez\u0151dцtt"

    Message
    "A <%AppName%> alkalmazбs el lett tбvolнtva a rendszerйr\u0151l."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Eltбvolнtбs rйszletei"

    Subtitle
    "Az eltбvolнtбs alatt hiba lйpett fel!"

    Caption
    "A kцvetkez\u0151 hibбk lйptek fel az eltбvolнtбs alatt:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Vбsбrlуi informбciуk"

    Subtitle
    "Kйrem нrja ide az informбciуkat."

    Caption
    "Kйrem нrja be a nevйt йs a munkahelyйnek nevйt."

    Message
    ""

    UserNameLabel
    "Felhasznбlу neve:"

    CompanyLabel
    "Cйg:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Isten hozta a <%AppName%> InstallJammer Varбzslуjбban"

    Message
    "Ez a <%AppName%> alkalmazбs <%Version%> verziуjбt fogja telepнteni\
	a szбmнtуgйpйre.\n\n Javasoljuk, hogy zбrjon be minden alkalmazбst,\
	miel\u0151tt folytatnб.\n\n Kattintson a <%Next%> gombra a folytatбshoz\
	vagy a <%Cancel%> gombra kilйpйshez."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Jelszavas telepнtйs"

    Subtitle
    "Ez a telepнtйs egy jelszуt igйnyel a folytatбshoz."

    Caption
    "Kйrem gйpelje be a jelszуt."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
