ChooseComponents {
    Title
    "Pasirenkamasis бdiegimas"

    Subtitle
    "Pasirinkite komponentus kuriuos diegimo programa бdiegs."

    Caption
    "Paюymлkite komponentus kuriuos norite бdiegti ir atюymлkite\
     tuos kuriuos nenorite бdiegti."


    Message
    "Reikлs <%SpaceRequiredText%> talpos"

    DescriptionLabel
    "Apraрymas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Diegiama"

    Subtitle
    "Diegiama <%AppName%>"

    Caption
    "Praрom palaukti kol diegimo programa бdiegs <%AppName%> б jыsш kompiuterб."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Бveskite pavadinimа."

    Message
    "Бveskite praneрimа."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Antraрtл"

    Subtitle
    "Paantraрtл"

    Caption
    "Pavadinimas"

    Message
    "Praneрimas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Antraрtл"

    Subtitle
    "Paantraрtл"

    Caption
    "Pavadinimas"

    Message
    "Praneрimas"

    Text
    "Бveskite pasirinktа teskta."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Sutikimas su licencija"

    Subtitle
    "raрom perskaityti рб sutikimа su licencija."

    Text
    "Patalpinkite иia savo licencijа."

    AcceptRadiobutton
    "Aр sutinku su licencija."

    DeclineRadiobutton
    "Aр nesutinku su licencija."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Skaityti daugiau informacijos"

    Subtitle
    "Skaityti daugiau informacijos apie <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    "Patalpinkite informacija."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Pasirinkite paskirties vietа"

    Subtitle
    "Kur turлtш bыti <%AppName%> бdiegta?"

    Caption
     "Diegimo programa бdiegs <%AppName%> б рб katalogа.\n\nTam kad instaliuoti\
     б рб katalogа, paspauskite <%Next%>.\n\nБdiegimui б kita katalogа,\
     paspauskite <%Browse%> ir pasirinkite kitа katalogа."

    Message
    ""

    BrowseText
    "Tam kad instaliuoti б рб katalogа, paspauskite <%Next%>. Бdiegimui б
     kita katalogа, paspauskite <%Browse%> ir pasirinkite kitа katalogа."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Paskirties katalogas"
}

SelectProgramFolder {
    Title
    "Pasirinkite programos katalogа"

    Subtitle
    "Praрom pasirinkite programos katalogа"

    Caption
    "Diegimo programa бkels programos ikonas б programш katalogа pavaizduotа\
     apaиioje.  Galite бvesti naujа katalogo pavadinimа arba pasirinkti iр\
     esanиiш.  Norлdami tжsti <%Next%>."

    Message
    ""

    ProgramFolderLabel
    "Programos katalogas:"

    FolderListLabel
    "Esantys katalogai:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Sukurti programos katalogus visiems vartotojams"
}

SetupComplete {
    Caption
    "InstallJammer vedlys pabaigл darbа"

    Message
    "Diegimo programa baigл diegti <%AppName%> б jыsш kompiuterб.  Paspauskite\
    <%Finish%>, kad uюbaigti diegimа."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Diegimo tipas"

    Subtitle
    "Pasirinkite diegimo tipа kurio pageidaujate."

    Caption
    "Pasirinkite diegimo tipа kurio pageidaujate."

    Message
    ""

    DescriptionLabel
    "Apraрymas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Pradedamas failш kopijavimas"

    Subtitle
    "Perюiыrлkite nustatymus prieр pradedant kopijuoti failus"

    Caption
    "Diegimo programa turi pakankamai informacijos, kad pradлti kopijuoti programos failus.\
     Jei norite perюiыrлti arba pakeisti nustatymus, spauskite <%Back%>. Jei nustatymai\
     tenkina, spauskite <%Next%>, kad pradлti kopijuoti failus."

    Message
    ""

    Text
    "Diegimo katalogas:
            <%InstallDir%>

    Diegimo tipas:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Uninstalling"

    Subtitle
    "Paрalinama <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Programos paрalinimas baigtas"

    Message
    "<%AppName%> buvo paрalinta iр jыsш sistemos."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Programos paрalinimas iрsamiau"

    Subtitle
    "Klaidos atsitikusios per programos paрalinimа"

    Caption
    "Klaidos atsitikusios per programos paрalinimа:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Vartotojo informacija"

    Subtitle
    "Praрome бvesti savo informacijа."

    Caption
    "Бveskite savo vardа ir organizacijа kurioje dirbate."

    Message
    ""

    UserNameLabel
    "Vartotojo vardas:"

    CompanyLabel
    "Organizacija:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Sveiki atvyke б <%AppName%> diegimo programа."

    Message
    "Pabrлюtinai patartina iрeiti iр visш Windows programш kurias esate\
     pasileidж. Spauskite <%Next%> tam, kad tжsti diegimа."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Diegimo slaptaюodis"

    Subtitle
    "Рiam diegimui reikia slaptaюodюio."

    Caption
    "Praрom бvesti slaptaюodб."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
